force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Allow_Multiple_Devices__c.field-meta.xml
<CustomField>
    <fullName>Allow_Multiple_Devices__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows attendees to join from multiple devices</description>
    <inlineHelpText>Select this checkbox to allow Attendees to join from multiple devices</inlineHelpText>
    <label>Allow Multiple Devices</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Crypto_Key__c.field-meta.xml
<CustomField>
    <fullName>Crypto_Key__c</fullName>
    <description>Setting containing the default Crypto Key used to encrypt and decrypt the record id.</description>
    <inlineHelpText>Setting containing the default Crypto Key used to encrypt and decrypt the record id. This can be replaced if required.</inlineHelpText>
    <label>Crypto Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Enforce_Login__c.field-meta.xml
<CustomField>
    <fullName>Enforce_Login__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Setting to enforce Attendees to log in to events to track attendance</description>
    <inlineHelpText>Select this checkbox to enforce Attendees to log in to events to track attendance.</inlineHelpText>
    <label>Enforce Login</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/HD_Video__c.field-meta.xml
<CustomField>
    <fullName>HD_Video__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Defaults video resolution to HD video</description>
    <inlineHelpText>Select this checkbox to enable HD video</inlineHelpText>
    <label>HD Video</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Host_Video__c.field-meta.xml
<CustomField>
    <fullName>Host_Video__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Setting to start the video when the host joins the webinar</description>
    <inlineHelpText>Select this checkbox to start the video when the host joins the webinar</inlineHelpText>
    <label>Host Video</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Join_Before_Host__c.field-meta.xml
<CustomField>
    <fullName>Join_Before_Host__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows participants to join before the host</description>
    <inlineHelpText>Select this checkbox to allow participants to join before the host</inlineHelpText>
    <label>Join Before Host</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Oauth_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Oauth_Account_Id__c</fullName>
    <description>The Account Id from the Zoom Server-To-Server OAuth App.</description>
    <inlineHelpText>Enter the Account Id from the Zoom Server-To-Server OAuth App.</inlineHelpText>
    <label>Oauth Account Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Oauth_Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Oauth_Client_Id__c</fullName>
    <description>The Client Id from the Zoom Server-To-Server OAuth App.</description>
    <inlineHelpText>Enter the Client Id from the Zoom Server-To-Server OAuth App.</inlineHelpText>
    <label>Oauth Client Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Oauth_client_secret__c.field-meta.xml
<CustomField>
    <fullName>Oauth_client_secret__c</fullName>
    <label>Oauth Client Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Oauth_Connection__c.field-meta.xml
<CustomField>
    <fullName>Oauth_Connection__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This setting enables the Oauth connection to Zoom. Disable this setting to disconnect the Oauth connection to Zoom.</description>
    <inlineHelpText>Enables the Oauth connection to Zoom. Disables the Oauth connection to Zoom.</inlineHelpText>
    <label>Oauth Connection</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Panelist_Video__c.field-meta.xml
<CustomField>
    <fullName>Panelist_Video__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Setting to start the video when panelists join the webinar</description>
    <inlineHelpText>Select this checkbox to start the video when panelists join the webinar</inlineHelpText>
    <label>Panelist Video</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Send_Thank_you_email_notification__c.field-meta.xml
<CustomField>
    <fullName>Send_Thank_you_email_notification__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Sends a Thank Thank you email notification at the end of the event.</description>
    <inlineHelpText>Select this checkbox to send a Thank Thank you email notification at the end of the event.</inlineHelpText>
    <label>Send Thank you email notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Share_Recording_URL__c.field-meta.xml
<CustomField>
    <fullName>Share_Recording_URL__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It enables to send the recording URL in the Thank you an email notification. The Thank you email notification should be enabled for this feature to work.</description>
    <inlineHelpText>Select this checkbox to send the recording URL in the Thank you email notification. The Thank you email notification should be enabled for this feature to work.</inlineHelpText>
    <label>Share Recording URL</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Site_URL__c.field-meta.xml
<CustomField>
    <fullName>Site_URL__c</fullName>
    <description>The site URL which is used to accept or decline the event invitation email  (e.g - https://datacoladasfzoom-developer-edition.ap5.force.com/).</description>
    <inlineHelpText>Enter the site URL which is used to accept or decline the event invitation email (e.g - https://datacoladasfzoom-developer-edition.ap5.force.com/).</inlineHelpText>
    <label>Site URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Start_Participant_Video_on_Join__c.field-meta.xml
<CustomField>
    <fullName>Start_Participant_Video_on_Join__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Setting to start the participant video on joining</description>
    <inlineHelpText>Select this checkbox to start the participant video on joining</inlineHelpText>
    <label>Start Participant Video on Join</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Zoom_Account_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Zoom_Account_User_Id__c</fullName>
    <description>Setting Containing the Zoom Account User Id, which is populated during Zoom Server-To-Server OAuth connection.</description>
    <inlineHelpText>Setting Containing the Zoom Account User Id, which is populated during Zoom Server-To-Server OAuth connection.</inlineHelpText>
    <label>Zoom Account User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Zoom_API_Page_Size__c.field-meta.xml
<CustomField>
    <fullName>Zoom_API_Page_Size__c</fullName>
    <defaultValue>&quot;100&quot;</defaultValue>
    <description>Setting that specifies the number of records to return per page in the API response.</description>
    <inlineHelpText>Setting that specifies the number of records to return per page in the API response.</inlineHelpText>
    <label>Zoom API Page Size</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Zoom_Integration_User_Email__c.field-meta.xml
<CustomField>
    <fullName>Zoom_Integration_User_Email__c</fullName>
    <description>The Zoom Account (Profile) User&apos;s Email address for whom meeting/webinar needs to be created.</description>
    <inlineHelpText>Enter the Zoom Account (Profile) User&apos;s Email address for whom meeting/webinar needs to be created.</inlineHelpText>
    <label>Zoom Integration User Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Zoom_URL__c.field-meta.xml
<CustomField>
    <fullName>Zoom_URL__c</fullName>
    <description>The Zoom org URL (e.g. https://zoom.us/)</description>
    <inlineHelpText>Enter the Zoom org URL (e.g. https://zoom.us/)</inlineHelpText>
    <label>Zoom URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Zoom_Webhook_Secret_Token__c.field-meta.xml
<CustomField>
    <fullName>Zoom_Webhook_Secret_Token__c</fullName>
    <description>The Secret Token from the Zoom Server-To-Server OAuth App. Used to verify event notifications sent by Zoom</description>
    <inlineHelpText>Enter the Secret Token from the Zoom Server-To-Server OAuth App. Used to verify event notifications sent by Zoom</inlineHelpText>
    <label>Zoom Webhook Secret Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SFZoom_SettingsControllerTest.cls
/*
    The MIT License
    Copyright © 2020 DataColada Pty Ltd

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
 */
/******************************************************************************************************************
    Class Name  : SFZoom_SettingsControllerTest
    Description :
    Date        : 07 Jan 2024.
    Author      : DataColada Pty Ltd
*******************************************************************************************************************/
@isTest
public class SFZoom_SettingsControllerTest {
    @TestSetup
    static void setup() {

        Zoom_Configuration_Settings__c zoomConfig = new Zoom_Configuration_Settings__c(
            Zoom_URL__c = 'https://zoom.us',
            Name = Label.Config_Details_Custom_Setting_Name,
            /*Oauth_client_secret__c = 'i1Fdydv5mSer3Oy1vvZCdD158S31HwUT',*/
              Oauth_client_secret__c = 'i1Fdfff5mSer3Oy1vdsCdD158S31HwUT',
            Zoom_API_Page_Size__c = '121',
            Start_Participant_Video_on_Join__c = false,
            Send_Thank_you_email_notification__c = true,
            Host_Video__c = false,
            /*Oauth_Account_Id__c = 'ELd7YI06QLuhVE6FHlZAPA',*/
            Oauth_Account_Id__c = 'ELd7YI06QKufGF8FHlZAPA',
            Share_Recording_URL__c = false,
            HD_Video__c = false,
            Join_Before_Host__c = false,
            Allow_Multiple_Devices__c = false,
            Share_Survey_Link__c = false,
            Enforce_Login__c = false,
            Panelist_Video__c = false,
            Site_URL__c = 'http://www.Test.URL.site1222.com',
            /*Zoom_Account_User_Id__c = 'udT2oat8QNqEKPoQdc4c7w',*/
            Zoom_Account_User_Id__c = 'udT2oat2GHqFDRoQdc4c9b',
            /*Oauth_Client_Id__c = 'WUGSZ5MDTwmM55OjpSR8cQ',*/
            Oauth_Client_Id__c = 'WUGSH6NHGwmM321jpSR8cQ',
            Oauth_Connection__c = true,
            /*Zoom_Webhook_Secret_Token__c = 'iDqi0fxwTVW0G30HjqouXg',*/
            Zoom_Webhook_Secret_Token__c = 'iDqi0fxwGHF0G30HjhgfXg',
            Zoom_Integration_User_Email__c = 'admin+test98@ausdn.org.au',
            Crypto_Key__c = 'r7f6uf6rerye'
        );

        // Insert the record
        insert zoomConfig;

    }

    @IsTest
    static void getZoomConfigurationSettingsTest() {
        Test.startTest();
        Zoom_Configuration_Settings__c result = SFZoom_SettingsController.getZoomConfigurationSettings();
        Test.stopTest();

        System.assertNotEquals(null, result, 'Zoom Configuration Settings should not be null');
        System.assertEquals('https://zoom.us', result.Zoom_URL__c, 'Zoom URL should match the test data');
        System.assertEquals('admin+test98@ausdn.org.au', result.Zoom_Integration_User_Email__c, 'Zoom User Email should match the test data');
    }

    @IsTest
    static void getZoomConfigurationSettings_NegativeTest() {

        delete [SELECT Id FROM Zoom_Configuration_Settings__c WHERE Name = :Label.Config_Details_Custom_Setting_Name];

        Test.startTest();
        Zoom_Configuration_Settings__c result = SFZoom_SettingsController.getZoomConfigurationSettings();
        Test.stopTest();

        System.assertEquals(null, result, 'Zoom Configuration Settings should be null if no configuration exists');
    }

    @IsTest
    static void createZoomConfigurationSettings_NewRecordTest() {
        delete [SELECT Id FROM Zoom_Configuration_Settings__c WHERE Name = :Label.Config_Details_Custom_Setting_Name];

        Map<String, Object> inputValues = new Map<String, Object>{
            'zoomUrl' => 'https://new.zoom.us',
            'zoomUserEmail' => 'new@test.com',
            'siteURL' => 'https://newsite.com',
            'zoomAccUserId' => 'newZoomUserId123',
            'cryptoKey' => 'newCryptoKey456',
            'zoomApiPageSz' => '200',
            'emailSenderName' => 'New Sender Name',
            'fromEmailAdd' => 'sender@test.com',
            'enforceLogin' => true,
            'thankEmailNotify' => true,
            'shareSurveyLink' => false,
            'shareRecUrl' => true,
            'minMeetDuration' => 15,
            'maxMeetDuration' => 300,
            'joinBeforeHost' => false,
            'startPartVideo' => true,
            'allowAttendes' => false,
            'byDefaultBroad' => true,
            'startVideoHostJoin' => true,
            'startVideoPaneJoin' => false,
            'accountId' => 'newAccountId789',
            'clientId' => 'newClientId101112',
            'clientSecret' => 'newClientSecret131415',
            'webhookSecretToken' => 'newWebhookToken161718'
        };


        Test.startTest();
        Boolean result = SFZoom_SettingsController.createZoomConfigurationSettings(inputValues);
        Test.stopTest();

        // System.assert(result, 'Record should be created successfully');

        List<Zoom_Configuration_Settings__c> createdRecord = [SELECT Zoom_URL__c, Zoom_Integration_User_Email__c, Site_URL__c
                                                        FROM Zoom_Configuration_Settings__c
                                                        WHERE Name = :Label.Config_Details_Custom_Setting_Name];
        // System.assertEquals('https://new.zoom.us', createdRecord.Zoom_URL__c, 'Zoom URL should match input values');
        // System.assertEquals('new@test.com', createdRecord.Zoom_Integration_User_Email__c, 'Zoom User Email should match input values');
        // System.assertEquals('https://newsite.com', createdRecord.Site_URL__c, 'Site URL should match input values');
    }




    @IsTest
    static void createZoomConfigurationSettings_UpdateRecordTest() {
        Map<String, Object> inputValues = new Map<String, Object>{
            'zoomUrl' => 'https://updated.zoom.us',
            'zoomUserEmail' => 'updated@test.com'
        };

        Test.startTest();
        Boolean result = SFZoom_SettingsController.createZoomConfigurationSettings(inputValues);
        Test.stopTest();

        System.assert(result, 'Record should be updated successfully');

        Zoom_Configuration_Settings__c updatedRecord = [SELECT Zoom_URL__c, Zoom_Integration_User_Email__c
                                                         FROM Zoom_Configuration_Settings__c
                                                         WHERE Name = :Label.Config_Details_Custom_Setting_Name];
        System.assertEquals('https://updated.zoom.us', updatedRecord.Zoom_URL__c, 'Zoom URL should be updated');
        System.assertEquals('updated@test.com', updatedRecord.Zoom_Integration_User_Email__c, 'Zoom User Email should be updated');
    }

    @IsTest
    static void getOAuthTestResponseTest() {
        // Test.setMock(HttpCalloutMock.class, new SFZoom_ServerToServerOauthMock());
        Test.setMock(HttpCalloutMock.class, new MockHttpCallout());

        Test.startTest();
        Zoom_Configuration_Settings__c createdRecord = [SELECT Zoom_URL__c, Zoom_Integration_User_Email__c, Site_URL__c
                                                        FROM Zoom_Configuration_Settings__c
                                                        WHERE Name = :Label.Config_Details_Custom_Setting_Name];
        String response = SFZoom_SettingsController.getOAuthTestResponse();
        Test.stopTest();

        System.assertEquals('Access Token Passed , Zoom User Email Passed', response, 'OAuth test response should match expected value');
    }


    private class MockHttpCallout implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();

            res.setBody('{"id": "udT2oat8QNqEKPoQdc4c7w" , "access_token" : "token1234" , "token_type" : "bearer" , "expires_in": "3599"}');
            res.setStatusCode(200);
            res.setStatus('OK');

            return res;
        }
    }
}