force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Allow_Multiple_Devices__c.field-meta.xml
<CustomField>
    <fullName>Allow_Multiple_Devices__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows attendees to join from multiple devices</description>
    <inlineHelpText>Select this checkbox to allow Attendees to join from multiple devices</inlineHelpText>
    <label>Allow Multiple Devices</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Crypto_Key__c.field-meta.xml
<CustomField>
    <fullName>Crypto_Key__c</fullName>
    <description>Setting containing the default Crypto Key used to encrypt and decrypt the record id.</description>
    <inlineHelpText>Setting containing the default Crypto Key used to encrypt and decrypt the record id. This can be replaced if required.</inlineHelpText>
    <label>Crypto Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Email_Sender_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Name__c</fullName>
    <description>It contains the sender name of the event invitation email</description>
    <inlineHelpText>Enter the sender name for the event invitation email which is sent to Contacts.</inlineHelpText>
    <label>Email Sender Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Enforce_Login__c.field-meta.xml
<CustomField>
    <fullName>Enforce_Login__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Setting to enforce Attendees to log in to events to track attendance</description>
    <inlineHelpText>Select this checkbox to enforce Attendees to log in to events to track attendance.</inlineHelpText>
    <label>Enforce Login</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/HD_Video__c.field-meta.xml
<CustomField>
    <fullName>HD_Video__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Defaults video resolution to HD video</description>
    <inlineHelpText>Select this checkbox to enable HD video</inlineHelpText>
    <label>HD Video</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Host_Video__c.field-meta.xml
<CustomField>
    <fullName>Host_Video__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Setting to start the video when the host joins the webinar</description>
    <inlineHelpText>Select this checkbox to start the video when the host joins the webinar</inlineHelpText>
    <label>Host Video</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Join_Before_Host__c.field-meta.xml
<CustomField>
    <fullName>Join_Before_Host__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows participants to join before the host</description>
    <inlineHelpText>Select this checkbox to allow participants to join before the host</inlineHelpText>
    <label>Join Before Host</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Maximum_Meeting_Duration__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Meeting_Duration__c</fullName>
    <description>It contains the value (minutes) for maximum meeting duration</description>
    <inlineHelpText>Enter the number of minutes for the maximum meeting duration (e.g. 120)</inlineHelpText>
    <label>Maximum Meeting Duration (In Minutes)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Minimum_Meeting_Duration__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Meeting_Duration__c</fullName>
    <description>It contains the value (minutes) for minimum meeting duration</description>
    <inlineHelpText>Enter the number of minutes for the minimum meeting duration (e.g. 15)</inlineHelpText>
    <label>Minimum Meeting Duration (In Minutes)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Panelist_Video__c.field-meta.xml
<CustomField>
    <fullName>Panelist_Video__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Setting to start the video when panelists join the webinar</description>
    <inlineHelpText>Select this checkbox to start the video when panelists join the webinar</inlineHelpText>
    <label>Panelist Video</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Send_Thank_you_email_notification__c.field-meta.xml
<CustomField>
    <fullName>Send_Thank_you_email_notification__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Sends a Thank Thank you email notification at the end of the event.</description>
    <inlineHelpText>Select this checkbox to send a Thank Thank you email notification at the end of the event.</inlineHelpText>
    <label>Send Thank you email notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Share_Recording_URL__c.field-meta.xml
<CustomField>
    <fullName>Share_Recording_URL__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It enables to send the recording URL in the Thank you an email notification. The Thank you email notification should be enabled for this feature to work.</description>
    <inlineHelpText>Select this checkbox to send the recording URL in the Thank you email notification. The Thank you email notification should be enabled for this feature to work.</inlineHelpText>
    <label>Share Recording URL</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Site_URL__c.field-meta.xml
<CustomField>
    <fullName>Site_URL__c</fullName>
    <description>The site URL which is used to accept or decline the event invitation email  (e.g - https://datacoladasfzoom-developer-edition.ap5.force.com/).</description>
    <inlineHelpText>Enter the site URL which is used to accept or decline the event invitation email (e.g - https://datacoladasfzoom-developer-edition.ap5.force.com/).</inlineHelpText>
    <label>Site URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Start_Participant_Video_on_Join__c.field-meta.xml
<CustomField>
    <fullName>Start_Participant_Video_on_Join__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Setting to start the participant video on joining</description>
    <inlineHelpText>Select this checkbox to start the participant video on joining</inlineHelpText>
    <label>Start Participant Video on Join</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Zoom_Account_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Zoom_Account_User_Id__c</fullName>
    <description>Setting Containing the Zoom Account User Id, which is populated during Zoom Server-To-Server OAuth connection.</description>
    <inlineHelpText>Setting Containing the Zoom Account User Id, which is populated during Zoom Server-To-Server OAuth connection.</inlineHelpText>
    <label>Zoom Account User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Zoom_Integration_User_Email__c.field-meta.xml
<CustomField>
    <fullName>Zoom_Integration_User_Email__c</fullName>
    <description>The Zoom Account (Profile) User&apos;s Email address for whom meeting/webinar needs to be created.</description>
    <inlineHelpText>Enter the Zoom Account (Profile) User&apos;s Email address for whom meeting/webinar needs to be created.</inlineHelpText>
    <label>Zoom Integration User Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Zoom_URL__c.field-meta.xml
<CustomField>
    <fullName>Zoom_URL__c</fullName>
    <description>The Zoom org URL (e.g. https://zoom.us/)</description>
    <inlineHelpText>Enter the Zoom org URL (e.g. https://zoom.us/)</inlineHelpText>
    <label>Zoom URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/SFZoom_ConfigDetailsControllerTest.cls
/*
    The MIT License
    Copyright © 2020 DataColada Pty Ltd

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
 */

/******************************************************************************************************************
    Class Name  : SFZoom_ConfigDetailsControllerTest
    Description : This class is responsible for testing all the operation of SFZoom_ConfigDetailsController Class.
    Date        : 01 Nov 2018.
    Author       : DataColada Pty Ltd
*******************************************************************************************************************/
@isTest(seeAllData = false)
public class SFZoom_ConfigDetailsControllerTest {

    /******************************************************************************************************************
        Method Name  : TestConfigDetailsControllerSaveAndEdit
        Description  : It verifies save and edit operation of the Zoom Configuration page.
        Date         : 01 Nov 2018.
        Author       : DataColada Pty Ltd
    *******************************************************************************************************************/
    @isTest
    static void TestConfigDetailsControllerSaveAndEdit(){
        Test.startTest();

        SFZoom_ConfigDetailsController controllerVar = new SFZoom_ConfigDetailsController();
        Test.setMock(HttpCalloutMock.class, new SFZoom_VerifyAuthAndSaveCalloutMock());


        System.assertEquals(false, controllerVar.isUpdate);
        System.assertEquals(false, controllerVar.isRecordExist);

        controllerVar.zoomAPIKey = 'Test_API_Key';
        controllerVar.ZoomAPISecret = 'Test_API_Secret';
        controllerVar.ZoomUserEmail = 'admin@datacolada.com';
        controllerVar.ZoomURL = 'https://zoom.us/j/';
        controllerVar.siteURL = 'https://datacoladasfzoom-developer-edition.ap5.force.com/';
        controllerVar.EmailSenderName = 'DataColada';
        controllerVar.joinBeforeHost = true;
        controllerVar.startParticipantVideo = true;
        controllerVar.enforceLogin = true;
        controllerVar.thankYouEmailNotification = true;
        controllerVar.shareSurveyLink = true;
        controllerVar.shareRecordingURL = true;


        controllerVar.minimumMeetingDuration = 0;
        controllerVar.maximumMeetingDuration = 0;
        controllerVar.joinBeforeHost = true;
        controllerVar.startParticipantVideo = true;
        controllerVar.allowMultipleDevices = true;
        controllerVar.defaultsToHDVideo = true;
        controllerVar.startVideoWhenHostJoin = true;
        controllerVar.startVideoWhenPanelistJoin = true;
        controllerVar.SaveConfigurationDetails();


        controllerVar.minimumMeetingDuration = 10;
        controllerVar.maximumMeetingDuration = 100;
        controllerVar.SaveConfigurationDetails();

        Zoom_Configuration_Settings__c zoomConfigurationDetails = Zoom_Configuration_Settings__c.getValues(Label.Config_Details_Custom_Setting_Name);
        // system.debug('zoomConfigurationDetails'+zoomConfigurationDetails);
        // System.assertEquals('Test_API_Key', zoomConfigurationDetails.Zoom_API_Key__c);
        // System.assertEquals('Test_API_Secret', zoomConfigurationDetails.Zoom_API_Secret__c);
        // System.assertEquals('https://zoom.us/j/', zoomConfigurationDetails.Zoom_URL__c);
        // System.assertEquals(true, zoomConfigurationDetails.Enforce_Login__c);
        // System.assertNotEquals(0, zoomConfigurationDetails.Maximum_Meeting_Duration__c);
        // System.assertNotEquals(0, zoomConfigurationDetails.Minimum_Meeting_Duration__c);
        // System.assertEquals(100, zoomConfigurationDetails.Maximum_Meeting_Duration__c);
        // System.assertEquals(10, zoomConfigurationDetails.Minimum_Meeting_Duration__c);
        // System.assertNotEquals(false, zoomConfigurationDetails.Join_Before_Host__c);

        controllerVar.EditConfigurationDetails();
        System.assertEquals(true, controllerVar.isUpdate);
        controllerVar.CancelConfigurationDetails();
        Test.stopTest();
        System.assertEquals(false, controllerVar.isUpdate);
    }

    /******************************************************************************************************************
        Method Name  : TestConfigDetailsControllerLoadConfigEditAndSave
        Description  : It verifies load existing configuration, edit and save operation of the Zoom Configuration page.
        Date         : 01 Nov 2018.
        Author       : DataColada Pty Ltd
    *******************************************************************************************************************/
    @isTest
    static void TestConfigDetailsControllerLoadConfigEditAndSave(){

        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        Zoom_Configuration_Settings__c zoomConfigurationDetails = new Zoom_Configuration_Settings__c();
        zoomConfigurationDetails.Name = 'Zoom Settings';

        zoomConfigurationDetails.Zoom_API_Key__c = 'Test_API_Key';
        zoomConfigurationDetails.Zoom_API_Secret__c = 'Test_API_Secret';
        zoomConfigurationDetails.Zoom_Integration_User_Email__c = 'admin@datacolada.com';
        zoomConfigurationDetails.Zoom_URL__c = 'https://zoom.us/j/';
        zoomConfigurationDetails.Site_URL__c = 'https://datacoladasfzoom-developer-edition.ap5.force.com/';
        zoomConfigurationDetails.Email_Sender_Name__c = 'DataColada';
        zoomConfigurationDetails.Enforce_Login__c = true;
        zoomConfigurationDetails.Join_Before_Host__c = true;
        zoomConfigurationDetails.Start_Participant_Video_on_Join__c = true;

        zoomConfigurationDetails.Maximum_Meeting_Duration__c = 30;
        zoomConfigurationDetails.Minimum_Meeting_Duration__c = 20;

        zoomConfigurationDetails.Allow_Multiple_Devices__c = true;
        zoomConfigurationDetails.Crypto_Key__c = 'test1234';
        zoomConfigurationDetails.Zoom_Account_User_Id__c = 'testUserId';
                zoomConfigurationDetails.HD_Video__c = true;
        zoomConfigurationDetails.Host_Video__c = true;
        zoomConfigurationDetails.Panelist_Video__c = true;
        zoomConfigurationDetails.Zoom_Authorization_Token__c = 'test_authorization_token';
        zoomConfigurationDetails.Allow_Multiple_Devices__c = true;
        zoomConfigurationDetails.Send_Thank_you_email_notification__c = true;
        zoomConfigurationDetails.Share_Recording_URL__c = true;
        zoomConfigurationDetails.Share_Survey_Link__c = true;

        INSERT zoomConfigurationDetails;

        Zoom_Configuration_Settings__c zoomConfigurationDetailsInserted = Zoom_Configuration_Settings__c.getValues('Zoom Settings');
        System.assertNotEquals(null, zoomConfigurationDetailsInserted);

        SFZoom_ConfigDetailsController controllerVar = new SFZoom_ConfigDetailsController();

        System.assertEquals('Test_API_Key', controllerVar.zoomAPIKey);
        System.assertEquals('Test_API_Secret', controllerVar.ZoomAPISecret);
        System.assertNotEquals('https://zoom.us', controllerVar.ZoomURL);
        System.assertEquals(true, controllerVar.joinBeforeHost);
        System.assertEquals(true, controllerVar.startParticipantVideo);
        System.assertEquals(true, controllerVar.enforceLogin);
        System.assertEquals(true, controllerVar.thankYouEmailNotification);
        System.assertEquals(true, controllerVar.shareSurveyLink);
        System.assertEquals(true, controllerVar.shareRecordingURL);

        Test.startTest();
        controllerVar.EditConfigurationDetails();
        System.assertEquals(true, controllerVar.isUpdate);

        controllerVar.ZoomURL = 'https://zoom.us/j/';
        controllerVar.SaveConfigurationDetails();
        Test.stopTest();
        System.assertEquals('https://zoom.us/j/', zoomConfigurationDetails.Zoom_URL__c);
    }

    /******************************************************************************************************************
        Method Name  : testGetFromEmailOptions
        Description  : It verifies the send email.
        Date         : 27 sept 2024.
        Author       : DataColada Pty Ltd
    *******************************************************************************************************************/

    @isTest
    static void testGetFromEmailOptions() {

        // Create an instance of the class that contains the method
        SFZoom_ConfigDetailsController instance = new SFZoom_ConfigDetailsController();

        // Call the method
        List<SelectOption> options = instance.getFromEmailOptions();

        // Assert that the list is not null and contains the expected number of options
        System.assertNotEquals(null, options, 'The options list should not be null');
        //System.assertEquals(3, options.size(), 'There should be 2 options: Current User and Org Wide Email');

        // Assert the first option (Current User's Email)
        SelectOption currentUserOption = options[0];
        System.assertEquals(UserInfo.getUserEmail(), currentUserOption.getValue(), 'The first option should be the current user\'s email');
        System.assertEquals('Current User\'s Email Address <'+UserInfo.getUserEmail()+'>', currentUserOption.getLabel(), 'The label for the current user\'s email should be correct');

    }

    /******************************************************************************************************************
        Method Name  : testResetThankYouSetting
        Description  : It verifies the Reset Thankyou setting.
        Date         : 27 sept 2024.
        Author       : DataColada Pty Ltd
    *******************************************************************************************************************/

    static testMethod void testResetThankYouSetting() {
        SFZoom_ConfigDetailsController controller = new SFZoom_ConfigDetailsController();
        controller.thankYouEmailNotification = false;

        controller.resetThankYouSetting();

        System.assertEquals(false, controller.shareRecordingURL);
        System.assertEquals(false, controller.shareSurveyLink);
    }

     /******************************************************************************************************************
        Method Name  : testSFZoom_ConfigDetailsController
        Description  : It verifies load existing configuration, edit and save operation of the Zoom Configuration page.
        Date         : 30 sept 2024.
        Author       : DataColada Pty Ltd
    *******************************************************************************************************************/

     // Mock class for HTTP callout
    private class MockHttpResponseGenerator implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            // Create a mock response for the Zoom API
            HTTPResponse res = new HTTPResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setStatusCode(200);
            res.setBody('{"id": "mockZoomUserId"}'); // Mock response with a user ID
            return res;
        }
    }

    @isTest
    static void testSFZoom_ConfigDetailsController() {
        // Create a test Zoom Configuration Settings record
        Zoom_Configuration_Settings__c config = new Zoom_Configuration_Settings__c(
            Name = 'Test Config',
            Zoom_API_Key__c = 'testAPIKey',
            Zoom_API_Secret__c = 'testAPISecret'
        );

        insert config;

        // Instantiate the controller
        Test.startTest();

        SFZoom_ConfigDetailsController controller = new SFZoom_ConfigDetailsController();
        controller.zoomAPIKey = 'testAPIKey';
        controller.ZoomAPISecret = 'testAPISecret';

        // Test validation method
        controller.zoomAPIKey = '';
        Boolean isValid = controller.validateConfigurationDetails();
        System.assertEquals(false, isValid, 'Validation should fail when required fields are missing.');

        // Test VerifyAuthorizationTokenAndSaveUserId method
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        String accessToken = 'Bearer testAccessToken';
        String zoomUserEmail = 'testuser@example.com';
        String zoomAccountUserId = SFZoom_ConfigDetailsController.VerifyAuthorizationTokenAndSaveUserId(accessToken, zoomUserEmail);

        // Validate the returned user ID
        System.assertEquals('mockZoomUserId', zoomAccountUserId, 'The returned Zoom account user ID should match the mock response.');

        // Clean up
        delete config;

        Test.stopTest();
    }

     /******************************************************************************************************************
        Method Name  : TestSaveConfigurationDetails
        Description  : It verifies load existing configuration, edit and save operation of the Zoom Configuration page.
        Date         : 1 Oct 2024.
        Author       : DataColada Pty Ltd
    *******************************************************************************************************************/

        @isTest
    static void TestSaveConfigurationDetails() {
        // Set up the mock response for the HTTP callout
        Test.setMock(HttpCalloutMock.class, new SFZoom_VerifyAuthAndSaveCalloutMock());

        // Create a test Zoom Configuration Settings record
        Zoom_Configuration_Settings__c zoomConfigurationDetails = new Zoom_Configuration_Settings__c();
        zoomConfigurationDetails.Name = 'Zoom Settings';
        zoomConfigurationDetails.Zoom_API_Key__c = 'Test_API_Key';
        zoomConfigurationDetails.Zoom_API_Secret__c = 'Test_API_Secret';
        zoomConfigurationDetails.Zoom_Integration_User_Email__c = 'admin@datacolada.com';
        zoomConfigurationDetails.Zoom_Account_User_Id__c = 'testUserId';
        zoomConfigurationDetails.Zoom_Authorization_Token__c = 'test_authorization_token';

        INSERT zoomConfigurationDetails;

        Zoom_Configuration_Settings__c zoomConfigurationDetailsInserted = Zoom_Configuration_Settings__c.getValues('Zoom Settings');
        System.assertNotEquals(null, zoomConfigurationDetailsInserted, 'Inserted Zoom Configuration record should not be null.');

        // Call the method and verify the result
        Test.startTest();
        // Simulate the callout by invoking the method
        String AccountUserId = SFZoom_ConfigDetailsController.VerifyAuthorizationTokenAndSaveUserId(
            zoomConfigurationDetails.Zoom_Authorization_Token__c,
            zoomConfigurationDetails.Zoom_Integration_User_Email__c
        );

        Test.stopTest();

        // Assert that the zoomAccountUserId is set correctly based on the mock response
        //System.assertNotEquals('testUserId', AccountUserId, 'The Zoom account user ID should match the mock response.');
    }
 }