force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Allow_Multiple_Devices__c.field-meta.xml
<CustomField>
    <fullName>Allow_Multiple_Devices__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows attendees to join from multiple devices</description>
    <inlineHelpText>Select this checkbox to allow Attendees to join from multiple devices</inlineHelpText>
    <label>Allow Multiple Devices</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Crypto_Key__c.field-meta.xml
<CustomField>
    <fullName>Crypto_Key__c</fullName>
    <description>Setting containing the default Crypto Key used to encrypt and decrypt the record id.</description>
    <inlineHelpText>Setting containing the default Crypto Key used to encrypt and decrypt the record id. This can be replaced if required.</inlineHelpText>
    <label>Crypto Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Email_Sender_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Name__c</fullName>
    <description>It contains the sender name of the event invitation email</description>
    <inlineHelpText>Enter the sender name for the event invitation email which is sent to Contacts.</inlineHelpText>
    <label>Email Sender Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Enforce_Login__c.field-meta.xml
<CustomField>
    <fullName>Enforce_Login__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Setting to enforce Attendees to log in to events to track attendance</description>
    <inlineHelpText>Select this checkbox to enforce Attendees to log in to events to track attendance.</inlineHelpText>
    <label>Enforce Login</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/From_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>From_Email_Address__c</fullName>
    <description>It contains the sender email id of the event invitation email.</description>
    <inlineHelpText>Enter a valid email address for the sender email for the event invitation email.</inlineHelpText>
    <label>From Email Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/HD_Video__c.field-meta.xml
<CustomField>
    <fullName>HD_Video__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Defaults video resolution to HD video</description>
    <inlineHelpText>Select this checkbox to enable HD video</inlineHelpText>
    <label>HD Video</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Host_Video__c.field-meta.xml
<CustomField>
    <fullName>Host_Video__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Setting to start the video when the host joins the webinar</description>
    <inlineHelpText>Select this checkbox to start the video when the host joins the webinar</inlineHelpText>
    <label>Host Video</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Join_Before_Host__c.field-meta.xml
<CustomField>
    <fullName>Join_Before_Host__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows participants to join before the host</description>
    <inlineHelpText>Select this checkbox to allow participants to join before the host</inlineHelpText>
    <label>Join Before Host</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Maximum_Meeting_Duration__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Meeting_Duration__c</fullName>
    <description>It contains the value (minutes) for maximum meeting duration</description>
    <inlineHelpText>Enter the number of minutes for the maximum meeting duration (e.g. 120)</inlineHelpText>
    <label>Maximum Meeting Duration (In Minutes)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Minimum_Meeting_Duration__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Meeting_Duration__c</fullName>
    <description>It contains the value (minutes) for minimum meeting duration</description>
    <inlineHelpText>Enter the number of minutes for the minimum meeting duration (e.g. 15)</inlineHelpText>
    <label>Minimum Meeting Duration (In Minutes)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Oauth_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Oauth_Account_Id__c</fullName>
    <description>The Account Id from the Zoom Server-To-Server OAuth App.</description>
    <inlineHelpText>Enter the Account Id from the Zoom Server-To-Server OAuth App.</inlineHelpText>
    <label>Oauth Account Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Oauth_Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Oauth_Client_Id__c</fullName>
    <description>The Client Id from the Zoom Server-To-Server OAuth App.</description>
    <inlineHelpText>Enter the Client Id from the Zoom Server-To-Server OAuth App.</inlineHelpText>
    <label>Oauth Client Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Oauth_client_secret__c.field-meta.xml
<CustomField>
    <fullName>Oauth_client_secret__c</fullName>
    <label>Oauth Client Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Oauth_Connection__c.field-meta.xml
<CustomField>
    <fullName>Oauth_Connection__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This setting enables the Oauth connection to Zoom. Disable this setting to disconnect the Oauth connection to Zoom.</description>
    <inlineHelpText>Enables the Oauth connection to Zoom. Disables the Oauth connection to Zoom.</inlineHelpText>
    <label>Oauth Connection</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Panelist_Video__c.field-meta.xml
<CustomField>
    <fullName>Panelist_Video__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Setting to start the video when panelists join the webinar</description>
    <inlineHelpText>Select this checkbox to start the video when panelists join the webinar</inlineHelpText>
    <label>Panelist Video</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Send_Thank_you_email_notification__c.field-meta.xml
<CustomField>
    <fullName>Send_Thank_you_email_notification__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Sends a Thank Thank you email notification at the end of the event.</description>
    <inlineHelpText>Select this checkbox to send a Thank Thank you email notification at the end of the event.</inlineHelpText>
    <label>Send Thank you email notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Share_Recording_URL__c.field-meta.xml
<CustomField>
    <fullName>Share_Recording_URL__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It enables to send the recording URL in the Thank you an email notification. The Thank you email notification should be enabled for this feature to work.</description>
    <inlineHelpText>Select this checkbox to send the recording URL in the Thank you email notification. The Thank you email notification should be enabled for this feature to work.</inlineHelpText>
    <label>Share Recording URL</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Site_URL__c.field-meta.xml
<CustomField>
    <fullName>Site_URL__c</fullName>
    <description>The site URL which is used to accept or decline the event invitation email  (e.g - https://datacoladasfzoom-developer-edition.ap5.force.com/).</description>
    <inlineHelpText>Enter the site URL which is used to accept or decline the event invitation email (e.g - https://datacoladasfzoom-developer-edition.ap5.force.com/).</inlineHelpText>
    <label>Site URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Start_Participant_Video_on_Join__c.field-meta.xml
<CustomField>
    <fullName>Start_Participant_Video_on_Join__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Setting to start the participant video on joining</description>
    <inlineHelpText>Select this checkbox to start the participant video on joining</inlineHelpText>
    <label>Start Participant Video on Join</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Zoom_Account_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Zoom_Account_User_Id__c</fullName>
    <description>Setting Containing the Zoom Account User Id, which is populated during Zoom Server-To-Server OAuth connection.</description>
    <inlineHelpText>Setting Containing the Zoom Account User Id, which is populated during Zoom Server-To-Server OAuth connection.</inlineHelpText>
    <label>Zoom Account User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Zoom_API_Page_Size__c.field-meta.xml
<CustomField>
    <fullName>Zoom_API_Page_Size__c</fullName>
    <defaultValue>&quot;100&quot;</defaultValue>
    <description>Setting that specifies the number of records to return per page in the API response.</description>
    <inlineHelpText>Setting that specifies the number of records to return per page in the API response.</inlineHelpText>
    <label>Zoom API Page Size</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Zoom_Integration_User_Email__c.field-meta.xml
<CustomField>
    <fullName>Zoom_Integration_User_Email__c</fullName>
    <description>The Zoom Account (Profile) User&apos;s Email address for whom meeting/webinar needs to be created.</description>
    <inlineHelpText>Enter the Zoom Account (Profile) User&apos;s Email address for whom meeting/webinar needs to be created.</inlineHelpText>
    <label>Zoom Integration User Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Zoom_URL__c.field-meta.xml
<CustomField>
    <fullName>Zoom_URL__c</fullName>
    <description>The Zoom org URL (e.g. https://zoom.us/)</description>
    <inlineHelpText>Enter the Zoom org URL (e.g. https://zoom.us/)</inlineHelpText>
    <label>Zoom URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Zoom_Webhook_Secret_Token__c.field-meta.xml
<CustomField>
    <fullName>Zoom_Webhook_Secret_Token__c</fullName>
    <description>The Secret Token from the Zoom Server-To-Server OAuth App. Used to verify event notifications sent by Zoom</description>
    <inlineHelpText>Enter the Secret Token from the Zoom Server-To-Server OAuth App. Used to verify event notifications sent by Zoom</inlineHelpText>
    <label>Zoom Webhook Secret Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SFZoom_SettingsController.cls
/*
    The MIT License
    Copyright © 2020 DataColada Pty Ltd

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
 */
/******************************************************************************************************************
    Class Name  : SFZoom_SettingsController
    Description : This class is responsible for saving configuration details for Salesforce and Zoom Integration.
    Date        : 02 Jan 2024.
    Author       : DataColada Pty Ltd
*******************************************************************************************************************/
public with sharing class SFZoom_SettingsController {

    /******************************************************************************************************************
    Class Name  : SFZoom_SettingsController
    Description : This method is responsible for retreiving configuration details forom Salesforce .
    Date        : 02 Jan 2024.
    Author       : DataColada Pty Ltd
    *******************************************************************************************************************/
    @AuraEnabled(cacheable=true)
    public static Zoom_Configuration_Settings__c getZoomConfigurationSettings() {
        try {
            String configName = Label.Config_Details_Custom_Setting_Name;
            Zoom_Configuration_Settings__c zoomConfig = Zoom_Configuration_Settings__c.getValues(configName);

            if(zoomConfig != null) {
                //use the default key if the user has not supplied one
                if(zoomConfig.Crypto_Key__c == null) {
                    zoomConfig.Crypto_Key__c = Label.Default_Crypto_Key;
                }

                return zoomConfig;
            }else{
                System.debug('Please contact your system administrator to verify the Zoom Configuration Settings ');
                return null;
            }

        } catch (Exception e) {
            System.debug('Error in retrieving Zoom Configuration Settings: ' + e.getMessage());
            return null;
        }
    }

    /******************************************************************************************************************
    Class Name  : SFZoom_SettingsController
    Description : This method is responsible for saving configuration details for Salesforce and Zoom Integration.
    Date        : 02 Jan 2024.
    Author       : DataColada Pty Ltd
    *******************************************************************************************************************/
    @AuraEnabled
    public static Boolean createZoomConfigurationSettings(Map<String, Object> inputValues) {

        try {
            String name = System.Label.Config_Details_Custom_Setting_Name;

            Zoom_Configuration_Settings__c zoomConfigurationDetails =  Zoom_Configuration_Settings__c.getValues(name);

            // ** If the record doesn't exist, create a new instance
            if (zoomConfigurationDetails == null) {
                zoomConfigurationDetails = new Zoom_Configuration_Settings__c();
                zoomConfigurationDetails.Name = name;
            }

            if (inputValues.containsKey('zoomUrl')) {
                zoomConfigurationDetails.Zoom_URL__c = (String) inputValues.get('zoomUrl');
            }
            if (inputValues.containsKey('zoomUserEmail')) {
                zoomConfigurationDetails.Zoom_Integration_User_Email__c = (String) inputValues.get('zoomUserEmail');
            }
            if (inputValues.containsKey('siteURL')) {
                zoomConfigurationDetails.Site_URL__c = (String) inputValues.get('siteURL');
            }
            if (inputValues.containsKey('zoomAccUserId')) {
                zoomConfigurationDetails.Zoom_Account_User_Id__c = (String) inputValues.get('zoomAccUserId');
            }
            if (inputValues.containsKey('cryptoKey')) {
                zoomConfigurationDetails.Crypto_Key__c = (String) inputValues.get('cryptoKey');
            }
            if (inputValues.containsKey('zoomApiPageSz')) {
                zoomConfigurationDetails.Zoom_API_Page_Size__c = (String) inputValues.get('zoomApiPageSz');
            }
            if (inputValues.containsKey('emailSenderName')) {
                zoomConfigurationDetails.Email_Sender_Name__c = (String) inputValues.get('emailSenderName');
            }
            if (inputValues.containsKey('fromEmailAdd')) {
                zoomConfigurationDetails.From_Email_Address__c = (String) inputValues.get('fromEmailAdd');
            }
            if (inputValues.containsKey('enforceLogin')) {
                zoomConfigurationDetails.Enforce_Login__c = (Boolean) inputValues.get('enforceLogin');
            }
            if (inputValues.containsKey('thankEmailNotify')) {
                zoomConfigurationDetails.Send_Thank_you_email_notification__c = (Boolean) inputValues.get('thankEmailNotify');
            }
            if (inputValues.containsKey('shareSurveyLink')) {
                zoomConfigurationDetails.Share_Survey_Link__c = (Boolean) inputValues.get('shareSurveyLink');
            }
            if (inputValues.containsKey('shareRecUrl')) {
                zoomConfigurationDetails.Share_Recording_URL__c = (Boolean) inputValues.get('shareRecUrl');
            }
            if (inputValues.containsKey('minMeetDuration')) {
                zoomConfigurationDetails.Minimum_Meeting_Duration__c =  Decimal.valueOf((String) inputValues.get('minMeetDuration'));
            }
            if (inputValues.containsKey('maxMeetDuration')) {
                zoomConfigurationDetails.Maximum_Meeting_Duration__c =  Decimal.valueOf((String) inputValues.get('maxMeetDuration'));
            }
            if (inputValues.containsKey('joinBeforeHost')) {
                zoomConfigurationDetails.Join_Before_Host__c = (Boolean) inputValues.get('joinBeforeHost');
            }
            if (inputValues.containsKey('startPartVideo')) {
                zoomConfigurationDetails.Start_Participant_Video_on_Join__c = (Boolean) inputValues.get('startPartVideo');
            }
            if (inputValues.containsKey('allowAttendes')) {
                zoomConfigurationDetails.Allow_Multiple_Devices__c = (Boolean) inputValues.get('allowAttendes');
            }
            if (inputValues.containsKey('byDefaultBroad')) {
                zoomConfigurationDetails.HD_Video__c = (Boolean) inputValues.get('byDefaultBroad');
            }
            if (inputValues.containsKey('startVideoHostJoin')) {
                zoomConfigurationDetails.Host_Video__c = (Boolean) inputValues.get('startVideoHostJoin');
            }
            if (inputValues.containsKey('startVideoPaneJoin')) {
                zoomConfigurationDetails.Panelist_Video__c = (Boolean) inputValues.get('startVideoPaneJoin');
            }
            // **  Oauth=========
            if (inputValues.containsKey('accountId')) {
                zoomConfigurationDetails.Oauth_Account_Id__c = (String) inputValues.get('accountId');
            }
            if (inputValues.containsKey('clientId')) {
                zoomConfigurationDetails.Oauth_Client_Id__c = (String) inputValues.get('clientId');
            }
            if (inputValues.containsKey('clientSecret')) {
                zoomConfigurationDetails.oauth_client_secret__c = (String) inputValues.get('clientSecret');
            }
            if (inputValues.containsKey('webhookSecretToken')) {
                zoomConfigurationDetails.Zoom_Webhook_Secret_Token__c = (String) inputValues.get('webhookSecretToken');
            }
            if (inputValues.containsKey('enableOAuth')) {
                zoomConfigurationDetails.Oauth_Connection__c = (Boolean) inputValues.get('enableOAuth');
            }
            // upsert zoomConfigurationDetails;
            Database.upsertResult saveResult =  Database.upsert(zoomConfigurationDetails, Zoom_Configuration_Settings__c.Name);
            if (saveResult.isSuccess()){
                return true;
            } else{
                return false;
            }
        } catch (Exception e) {
            System.debug('Error in creating or updating record: ' + e.getMessage());
            return false;
        }
    }
    /******************************************************************************************************************
    Class Name  : SFZoom_SettingsController
    Description : This method is responsible for aouth response for Salesforce and Zoom Integration.
    Date        : 02 Jan 2024.
    Author      : DataColada Pty Ltd

    History
    -----------------
    13-01-2025  DataColada Pty Ltd connecting controller to the auth server
    *******************************************************************************************************************/
    @AuraEnabled
    public static String getOAuthTestResponse() {

        try {
            return  checkAccessTokenForSuccess();

        } catch (Exception e) {
            return 'Error in OAuth test: ' + e.getMessage() + '. Please check your oauth configuration';
        }
    }
    /**
     * @description       :
     * @author            : DataColada Pty Ltd
     * @last modified on  : 13-01-2025
     * @last modified by  : DataColada Pty Ltd
    **/
    private static String checkAccessTokenForSuccess() {
        String retCode;

        String access_token = SFZoom_ServerToServerOauth.Instance().getAccessToken();
        if (access_token == null) {
            return retCode =  'Error obtaining access token';
        }

        if( (retCode = checkForValidZoomUserEmail(access_token)) == null) {
            retCode =  'Access Token Passed , Zoom User Email Passed';
        }

        return retCode;
    }
    /**
     * @description       :
     * @author            : DataColada Pty Ltd
     * @last modified on  : 13-01-2025
     * @last modified by  : DataColada Pty Ltd
    **/
    private static String checkForValidZoomUserEmail(String access_token) {
        String retCode;
        Zoom_Configuration_Settings__c zoomConfig = Zoom_Configuration_Settings__c.getValues(Label.Config_Details_Custom_Setting_Name);

        String email = zoomConfig?.Zoom_Integration_User_Email__c;
        String zoomAccountUserId = SFZoom_ConfigDetailsController.VerifyAuthorizationTokenAndSaveUserId( 'Bearer ' + access_token, email);

        if(zoomAccountUserId == null) {
            retCode = 'Error getting Zoom Account Id : Please check you have configured the correct zoom integration user email.';
        }
        else {
            //check the cache , persist if not equal
            if( zoomConfig != null && zoomConfig.Zoom_Account_User_Id__c != zoomAccountUserId){
                zoomConfig.Zoom_Account_User_Id__c = zoomAccountUserId;
                update zoomConfig;
            }
        }

        return retCode;
    }

}